#!/usr/bin/env bash
# Run on the REMOTE server (AutoDL, cloud VM, etc.).
# Point shell HTTP(S)_PROXY at the SSH reverse-tunnel port on 127.0.0.1:7890.
#
# Usage:
#   ./proxy-server.sh on            # enable proxy in current shell
#   ./proxy-server.sh on --persist  # also auto-load in new shells (~/.bashrc)
#   ./proxy-server.sh off           # disable proxy
#   ./proxy-server.sh status        # check tunnel + env
#   ./proxy-server.sh test          # test connectivity
#   eval "$(./proxy-server.sh env)" # print export lines for eval

set -euo pipefail

PROXY_PORT="${PROXY_PORT:-7890}"
ENV_FILE="${ENV_FILE:-$HOME/.local-proxy.env}"
BASHRC_MARKER="# >>> local-proxy via SSH tunnel >>>"
HTTP_PROXY_URL="http://127.0.0.1:${PROXY_PORT}"
# Only PROXY_PORT is forwarded via SSH -R; use HTTP for ALL_PROXY as well.
ALL_PROXY_URL="http://127.0.0.1:${PROXY_PORT}"
NO_PROXY="localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"

port_open() {
  (echo >/dev/tcp/127.0.0.1/"$1") 2>/dev/null
}

check_tunnel() {
  if port_open "$PROXY_PORT"; then
    echo "OK: Tunnel port 127.0.0.1:${PROXY_PORT} is open"
    return 0
  fi
  echo "FAIL: 127.0.0.1:${PROXY_PORT} not reachable"
  echo ""
  echo "On your LOCAL machine, start the tunnel first:"
  echo "  ./tunnel-local.sh"
  return 1
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by proxy-server.sh — do not edit manually
export http_proxy="${HTTP_PROXY_URL}"
export https_proxy="${HTTP_PROXY_URL}"
export HTTP_PROXY="${HTTP_PROXY_URL}"
export HTTPS_PROXY="${HTTP_PROXY_URL}"
export ALL_PROXY="${ALL_PROXY_URL}"
export all_proxy="${ALL_PROXY_URL}"
export no_proxy="${NO_PROXY}"
export NO_PROXY="${NO_PROXY}"
EOF
}

enable_persist() {
  write_env_file
  if grep -qF "$BASHRC_MARKER" "$HOME/.bashrc" 2>/dev/null; then
    return 0
  fi
  cat >>"$HOME/.bashrc" <<EOF

${BASHRC_MARKER}
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi
# <<< local-proxy via SSH tunnel <<<
EOF
  echo "Persisted: new shells will auto-load $ENV_FILE"
}

cmd_on() {
  local persist=false
  if [[ "${1:-}" == "--persist" ]]; then
    persist=true
  fi

  check_tunnel || exit 1

  export http_proxy="$HTTP_PROXY_URL"
  export https_proxy="$HTTP_PROXY_URL"
  export HTTP_PROXY="$HTTP_PROXY_URL"
  export HTTPS_PROXY="$HTTP_PROXY_URL"
  export ALL_PROXY="$ALL_PROXY_URL"
  export all_proxy="$ALL_PROXY_URL"
  export no_proxy="$NO_PROXY"
  export NO_PROXY="$NO_PROXY"

  write_env_file

  if [[ "$persist" == "true" ]]; then
    enable_persist
  fi

  echo "Proxy enabled for current shell."
  echo "  HTTP/HTTPS -> ${HTTP_PROXY_URL}"
  echo "  ALL_PROXY  -> ${ALL_PROXY_URL}"
  echo ""
  echo "Quick test: $0 test"
  if [[ "$persist" != "true" ]]; then
    echo "New shell:  source $ENV_FILE"
  fi
}

cmd_off() {
  unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY
  unset ALL_PROXY all_proxy no_proxy NO_PROXY
  rm -f "$ENV_FILE"

  if [[ -f "$HOME/.bashrc" ]]; then
    sed -i "/${BASHRC_MARKER}/,/# <<< local-proxy via SSH tunnel <<</d" "$HOME/.bashrc" 2>/dev/null || true
  fi

  echo "Proxy disabled."
}

cmd_env() {
  cat <<EOF
export http_proxy="${HTTP_PROXY_URL}"
export https_proxy="${HTTP_PROXY_URL}"
export HTTP_PROXY="${HTTP_PROXY_URL}"
export HTTPS_PROXY="${HTTP_PROXY_URL}"
export ALL_PROXY="${ALL_PROXY_URL}"
export all_proxy="${ALL_PROXY_URL}"
export no_proxy="${NO_PROXY}"
export NO_PROXY="${NO_PROXY}"
EOF
}

cmd_status() {
  echo "=== Tunnel ==="
  if port_open "$PROXY_PORT"; then
    echo "  127.0.0.1:${PROXY_PORT}  OPEN"
  else
    echo "  127.0.0.1:${PROXY_PORT}  CLOSED"
  fi

  echo ""
  echo "=== Environment ==="
  for var in http_proxy https_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY; do
    if [[ -n "${!var:-}" ]]; then
      echo "  $var=${!var}"
    else
      echo "  $var=(unset)"
    fi
  done

  echo ""
  echo "=== Env file ==="
  if [[ -f "$ENV_FILE" ]]; then
    echo "  $ENV_FILE exists"
  else
    echo "  $ENV_FILE not found"
  fi
}

cmd_test() {
  check_tunnel || exit 1

  # shellcheck disable=SC1090
  [[ -f "$ENV_FILE" ]] && source "$ENV_FILE"

  echo "Testing via ${HTTP_PROXY_URL} ..."
  echo ""

  echo -n "  ipinfo.io (IP): "
  curl -fsS --max-time 15 --proxy "$HTTP_PROXY_URL" https://ipinfo.io/ip 2>/dev/null || echo "FAILED"

  echo -n "  google.com:     "
  if curl -fsSI --max-time 15 --proxy "$HTTP_PROXY_URL" https://www.google.com 2>/dev/null | head -1; then
    :
  else
    echo "FAILED"
  fi

  echo -n "  github.com:     "
  if curl -fsSI --max-time 15 --proxy "$HTTP_PROXY_URL" https://github.com 2>/dev/null | head -1; then
    :
  else
    echo "FAILED"
  fi
}

usage() {
  cat <<EOF
Usage: $0 <command> [options]

Commands:
  on [--persist]   Enable proxy (optionally persist in ~/.bashrc)
  off              Disable proxy
  status           Show tunnel and env status
  test             Test proxy connectivity
  env              Print export statements (for: eval "\$(\$0 env)")

Tunnel must be started from LOCAL machine:
  ./tunnel-local.sh
EOF
}

main() {
  case "${1:-}" in
    on)   shift; cmd_on "${1:-}" ;;
    off)  cmd_off ;;
    status) cmd_status ;;
    test) cmd_test ;;
    env)  cmd_env ;;
    -h|--help|"") usage ;;
    *) echo "Unknown command: $1" >&2; usage; exit 1 ;;
  esac
}

main "$@"
